### ISSUE TITLE
Cygwin已經不支援32bit要如何編譯專案?

### ISSUE THREAD

**Issue by pomelo0424** [Ameba-AIoT/ameba-rtos-z2#3]
### Answers checklist.

- [X] I have read the documentation, but the issue is not addressed there.
- [X] I have updated my ameba-rtos-z2 branch to the latest version and confirmed that the issue is still present.
- [X] I have searched the issue tracker([closed](https://github.com/Ameba-AIoT/ameba-rtos-z2/issues?q=is%3Aissue+label%3AType%3A+Bug+is%3Aclosed) and [existing](https://github.com/Ameba-AIoT/ameba-rtos-z2/issues?q=is%3Aissue+label%3AType%3A+Bug+is%3Aopen)) but did not find a similar issue.

### Contact details

youming@mct.com.tw

### Ameba-rtos-z2 version.

26dad548

### Ameba-rtos-z2 chip.

RTL8720CM

### External hardware.

無

### Compile system used.

Windows

### What is the expected behavior?

編譯成功或失敗

### What is the actual behavior?

make all後顯示下圖
![Snipaste_2024-09-26_16-17-56](https://github.com/user-attachments/assets/123e6a04-907e-4053-9c22-91be8dbc20cf)

### Relevant code.

```c
無
```

### Steps to reproduce.

1.在window10 64bit上安裝 cygwin
2.在安裝過程中安裝make與bc
3.安裝完成後開啟Cygwin Terminal
4.切換到專案路徑
5.make all 之後顯示 ONLY 32-BIT CYGWIN IS SUPPORTED!

### Relevant log output

```plain
love1@youming-hw ~
$ cd ..

love1@youming-hw /cygdrive/c
$ ls
'$MfeDeepRem'              Keil_v5                      TelinkSDK
'$Recycle.Bin'             MSOCache                     Users
'$WinREAgent'              MinGW                        WCH.CN
 AT32_test                 Nuvoton                      Windows
'Analog Devices'           OneDriveTemp                 cygwin64
 Cadence                   PEMicro                      devlist.txt
 Dell                      PerfLogs                     eSupport
'Documents and Settings'  'Program Files'               hiberfil.sys
 DumpStack.log            'Program Files (x86)'         opt
 DumpStack.log.tmp         ProgramData                  pagefile.sys
 Finish.log                Recovery                     swapfile.sys
 Hncb                      SPB_Data                     ti
 Intel                     SiliconLabs
 Keil_v4                  'System Volume Information'

love1@youming-hw /cygdrive/c
$ cd ..

love1@youming-hw /cygdrive
$ cd d/youming/study/matter_device/
FW/            HomeAssistant/ doc/

love1@youming-hw /cygdrive
$ cd d/youming/study/matter_device/FW/RTL8720/ameba-rtos-z2/
.git/                        component/
.github/                     doc/
.gitignore                   project/
README.md                    tools/
Realtek_Disclaimer-2019.pdf

love1@youming-hw /cygdrive
$ cd d/youming/study/matter_device/FW/RTL8720/ameba-rtos-z2/
.git/                        component/
.github/                     doc/
.gitignore                   project/
README.md                    tools/
Realtek_Disclaimer-2019.pdf

love1@youming-hw /cygdrive
$ cd d/youming/study/matter_device/FW/RTL8720/ameba-rtos-z2/project/realtek_amebaz2_v0_example/
GCC-RELEASE/     example_sources/ inc/             src/

love1@youming-hw /cygdrive
$ cd d/youming/study/matter_device/FW/RTL8720/ameba-rtos-z2/project/realtek_amebaz2_v0_example/
GCC-RELEASE/     example_sources/ inc/             src/

love1@youming-hw /cygdrive
$ cd d/youming/study/matter_device/FW/RTL8720/ameba-rtos-z2/project/realtek_amebaz2_v0_example/GCC-RELEASE/
Makefile                  application.is.amazon.mk  partition.json
Makefile.amazon           application.is.mk         rtl8710c_ram.ld
amebaz2_bootloader.json   keycfg.json               toolchain.mk
amebaz2_firmware_is.json  lib_amazon.mk

love1@youming-hw /cygdrive
$ cd d/youming/study/matter_device/FW/RTL8720/ameba-rtos-z2/project/realtek_amebaz2_v0_example/GCC-RELEASE/

love1@youming-hw /cygdrive/d/youming/study/matter_device/FW/RTL8720/ameba-rtos-z2/project/realtek_amebaz2_v0_example/GCC-RELEASE
$ make
Toolchain asdk-6.5.0-cygwin-newlib-build-3574-i686_amebaz2.tar.bz2 extracting...
ONLY 32-BIT CYGWIN IS SUPPORTED!
make: *** [toolchain.mk:46: toolchain] Error 255

love1@youming-hw /cygdrive/d/youming/study/matter_device/FW/RTL8720/ameba-rtos-z2/project/realtek_amebaz2_v0_example/GCC-RELEASE
$
```

### Additional information.

我有在32bit的window上安裝Cygwin  但無法安裝
也有在32bit的liunx上嘗試編譯該專案  但只顯示請用32bit的Cygwin

**Comment by renpeipei-realtek** [comment]
Hi @pomelo0424,

SDK可以支持Windows 和Linux 编译

1. Windows
可以参考以下link 安装Cygwin 32-bit version:
https://cygwin.com/pipermail/cygwin-announce/2022-November/010810.html

2. Linux
“也有在32bit的liunx上嘗試編譯該專案 但只顯示請用32bit的Cygwin”
您是否copy了在Windows中 extract的“\tools\arm-none-eabi-gcc\asdk”？
请确认download新的SDK至Linux，并重新make toolchain

谢谢~

**Comment by pomelo0424** [comment]
Hi @renpeipei-realtek 

1.Windows
   我嘗試了按照您給的方向去安裝
   但似乎依舊無法順利下載到32bit的Cygwin  所以我先嘗試liunx的編譯
2.liunx
   我clone了最新版本的SDK到我的虛擬機上
   但當我嘗試解壓縮asdk-6.5.0-linux-newlib-build-3574-x86_64_amebaz2.tar.bz2a
   出現了異常
![image](https://github.com/user-attachments/assets/b5cc5921-546a-4d3c-97b5-d322a70252b6)

我嘗試了使用bzip2recover修復他  但依舊不行

**Comment by renpeipei-realtek** [comment]
Hi @pomelo0424

1. Windows
https://cygwin.com/install.html#unsupported
可以尝试这个网页提供的“setup-x86.exe”

2. Linux
由于toolchain的size超过GitHub的single file limit，被分割成多个压缩包；所以不能直接解压缩 asdk-6.5.0-linux-newlib-build-3574-x86_64_amebaz2.tar.bz2a
SKD提供了command 解压缩toolchain：
- 在path “/project/.../GCC-RELEASE”，使用“make toolchain” 解压缩toolchain；或者
- 在path “/project/.../GCC-RELEASE”，使用“make all” 解压缩toolchain并编译SDK

**Comment by pomelo0424** [comment]
Hi @renpeipei-realtek 

1.Windows
   我嘗試下載後安裝出現下面的視窗   我也嘗試過在虛擬機上灌32bit的windows後執行該程式無法安裝
![image](https://github.com/user-attachments/assets/0c0483bf-2c8f-4703-8c22-237beafee539)
2.liunx
  我剛剛嘗試了您所說的方式
  出現叫我用64bit的cygwin的訊息  還有其他方式可以實驗嗎?
![image](https://github.com/user-attachments/assets/5ea8cdf8-4a30-49d9-80b3-e637a92e0f4a)

**Comment by renpeipei-realtek** [comment]
Hi @pomelo0424 

1. Windows
Option 1: 
(1) download Cygwin x86 version: https://www.cygwin.com/setup-x86.exe
(2) run this command in shell command:
setup-x86.exe --allow-unsupported-windows option --site http://ctm.crouchingtigerhiddenfruitbat.org/pub/cygwin/circa/2022/11/23/063457

Option 2:
http://www.crouchingtigerhiddenfruitbat.org/Cygwin/timemachine.html
请使用OLD UPDATE for 32-bit

2. Linux
请使用64 bit Linux version

**Comment by pomelo0424** [comment]
Hi @renpeipei-realtek 

感謝您的幫助
目前我將以cygwin 32bit 運行編譯環境

編譯完成沒有問題

感謝
